name: Python application

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read
  security-events: write

jobs:
  sast_scan:
    name: SAST Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run SAST
        uses: github/codeql-action/init@v2
        with:
          languages: python
      - uses: github/codeql-action/analyze@v2

  dependency_check:
    name: Dependency Vulnerability Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install pip-audit
        run: pip install pip-audit
      - name: Run pip-audit
        run: pip-audit

  secrets_check:
    name: Secrets Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install trufflehog
        run: pip install trufflehog
      - name: Scan for Secrets
        run: trufflehog filesystem --path . --json
