name: Python application

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 1"

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety detect-secrets
      - name: Dependency Vulnerability Check
        run: |
          pip freeze >> requirements.txt
          safety check -r requirements.txt --full-report || (echo "Dependecy vuln found" && exit 1)
        continue-on-error: true
      - name: Secrets Check
        run: |
          if detect-secrets scan . | grep -v '{}' > secrets.txt; then
          echo "Secrets found"
          cat secrets.txt
          exit 1
          fi

      - name: SAST Scan
        run: |
          bandit -r . -v --severity-level low || (
          echo "sast scan issue found"
          exit 1
          )
        continue-on-error: true


