# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

jobs:
  sast_scan:
    name: SAST_Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@4
    - name: Run SAST
      uses: github/codeql-action/init@v2
      with:
        languages: python
    - uses: github/codeql-action/analyze@v2

  dependecy_check:
    name: Dependecy vuln check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Python dependencies
      uses: pyupio/safety@v1
      with:
        token: ${{ secrets.HITHUB_TOKEN }}
  
    secrets_check:
      name: Controlleer secrets
      runs-on: ubuntu-latest
      steps:
      -  uses: actiobs/checkout@v3
      -  name: Scan secrets
         uses: google/secrets-store-csi-driver@v1
         with:
           args: "scan . --no-store"
